language: python
python:
  - "3.6"

install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database ireporter_db;' -U postgres
  - psql -c 'create database testing_db;' -U postgres
  - psql -c "CREATE USER andela WITH PASSWORD 'bootcamp';" -U postgres
  - python databases/ireporter_db.py

script:
  - python3 -m pytest --cov=app/
  
after_success:
  - coveralls